In [1]:
# Callin Switzer
# 23 May 2017
# Get all node values from a trained network, given a set of weights

In [5]:
import numpy as np
import pickle
import os
import pandas as pd

In [6]:
# this function returns values of all layers
def returnLayerValues(weights, inputData):
    '''
    Returns all layer values from fitted network (including input and output)
    
    The fitted network uses "tanh" activation for hidden layers and
        "linear" activation for the final layer
        
    Params:
        weights (list): list of weights from a fitted model
        inputData (array or Data frame): input data that will be run through the network
    
    Returns:
        layer values (list): values of all of the units in the network.
            - the 0'th item in the list is the input data
            - the final item in the list is the final prediction
    '''
    
    LayerValues = [inputData.astype("float64")]
    for layerNum in np.arange(0, len(wts), 2):
        
        # calculate dot product and add bias
        nextLayer = np.dot(LayerValues[-1], wts[layerNum]) + wts[layerNum+1]
        
        if layerNum != (len(wts)-2):
            # apply activation function, except for final layer
            nextLayer = np.tanh(nextLayer)
        
        # append to list
        LayerValues.append(nextLayer)
        
    return(LayerValues)

In [7]:
# load example data
pathToTrainingX= r"D:\Dropbox\AcademiaDropbox\UW\NNetVisualization\ExampleData\X_train_small.csv"
x_train = pd.read_csv(pathToTrainingX)

# in case you want to compare predicted to actual, you can load the Y dataset
pathToTrainingY= r"D:\Dropbox\AcademiaDropbox\UW\NNetVisualization\ExampleData\Y_train_small.csv"
y_train = pd.read_csv(pathToTrainingY)

In [9]:
# load weights
pathToWeights = r"D:\Dropbox\AcademiaDropbox\UW\NNetVisualization\ExampleData\Opt_rmsprop__Dro_0.0__Num_20_20_16__Wei_0_pruned_wts.pkl"

# read in weight data
wts =  pickle.load(open(pathToWeights, 'rb'))

# print sizes of each weight matrix
wtLengths = []
for ii in range(len(wts)):
    print(wts[ii].shape)
    wtLengths.append(np.prod(wts[ii].shape))

# print total number of weights (including biases)
print(np.sum(wtLengths), "total weights")

(10, 20)
(20,)
(20, 20)
(20,)
(20, 16)
(16,)
(16, 7)
(7,)
1095 total weights


In [16]:
# calculate values at each layer, using the function above
intermediateValues = returnLayerValues(wts, inputData= x_train)
len(intermediateValues)

5

In [18]:
# calculate intermediate values for only one input row
intermediateValues = returnLayerValues(wts, inputData= x_train.iloc[9, :])
intermediateValues

[phi_0          0.142728
 theta_0       -0.051374
 x_99          -0.189672
 y_99           0.038137
 phi_99         0.005685
 theta_99      -0.057947
 x_dot_0       -0.227377
 y_dot_0        0.085107
 phi_dot_0     -0.184476
 theta_dot_0   -0.226595
 Name: 9, dtype: float64,
 array([-0.02339151, -0.05434987, -0.03954071, -0.04073524, -0.0402231 ,
        -0.03642044,  0.02371522, -0.09060205, -0.04408416, -0.02665334,
         0.02554483, -0.03670677, -0.08306054,  0.07224588, -0.04319366,
        -0.02207429, -0.05884106, -0.11353568, -0.00442196,  0.02604794]),
 array([ 0.20628507,  0.04794674, -0.30728182,  0.01005733, -0.00977822,
         0.03256286,  0.05168823,  0.18786716, -0.15644673, -0.05612013,
         0.07292053,  0.02183338,  0.54625831, -0.06618114, -0.01574573,
        -0.01456413,  0.00579742,  0.07333504, -0.02280542,  0.04308808]),
 array([-0.09140476,  0.02169366, -0.016228  , -0.3850637 ,  0.18393699,
        -0.15647436,  0.07730785,  0.05184893, -0.0414717 ,  0.

In [19]:
! explorer .