In [ ]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from matplotlib.ticker import ScalarFormatter
import os
import pandas as pd
import time
from datetime import datetime
import sys
import seaborn as sns
import scipy.io
import subprocess
import winsound
import pickle
import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score
import tensorflow as tf
print("TensorFlow successfully installed.")
if tf.test.is_built_with_cuda():
    print("The installed version of TensorFlow includes GPU support.")
print(sys.version, "\n")
now = datetime.now()
print("last run on " + str(now))



from keras.layers import Input, Dense, Dropout, BatchNormalization
from keras.models import Model
from keras import regularizers

# Keras callcacks
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
import keras.backend as K

In [ ]:
# do a positive and a negative nnet weight cancel

In [3]:
X_train = np.random.rand(4,2 )

In [4]:
X_train.shape

(4, 2)

In [5]:
X_train

array([[0.06961859, 0.27180342],
       [0.63841609, 0.10032355],
       [0.34700694, 0.8659912 ],
       [0.46025331, 0.40371182]])

In [6]:
Y_train = np.random.rand(X_train.shape[0]).reshape(-1,1) + np.sum(X_train)

In [7]:
Y_train.shape

(4, 1)

In [64]:
K.clear_session()
inputs = Input(shape=(X_train.shape[1],))    

# add layers
x = Dense(2, activation='tanh', )(inputs)
#x = Dense(3, activation='tanh')(x)
predictions = Dense(Y_train.shape[1], activation='linear')(x)

# create model
model = Model(inputs=inputs, outputs=predictions)
model.compile(loss="mean_squared_error", optimizer = "rmsprop", metrics = ['mse'])

In [65]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [66]:
wts = model.get_weights().copy()

In [67]:
wts[0]

array([[-0.23489016,  1.0954024 ],
       [-1.1490151 , -0.58189243]], dtype=float32)

In [68]:
history = model.fit(X_train, Y_train, epochs = 3, verbose = 2, 
                        batch_size=16)

Epoch 1/3
 - 0s - loss: 19.4904 - mean_squared_error: 19.4904
Epoch 2/3
 - 0s - loss: 19.3558 - mean_squared_error: 19.3558
Epoch 3/3
 - 0s - loss: 19.2588 - mean_squared_error: 19.2588


In [69]:
wts = model.get_weights().copy()
wts

[array([[-0.22751574,  1.0880353 ],
        [-1.1416353 , -0.5892527 ]], dtype=float32),
 array([ 0.00737442, -0.00736383], dtype=float32),
 array([[ 1.2845858],
        [-0.9695439]], dtype=float32),
 array([0.00736855], dtype=float32)]

In [70]:
for ii in range(len(wts)):
    print(wts[ii], "\n")

[[-0.22751574  1.0880353 ]
 [-1.1416353  -0.5892527 ]] 

[ 0.00737442 -0.00736383] 

[[ 1.2845858]
 [-0.9695439]] 

[0.00736855] 



In [71]:
wts[0] = np.array([[1, 0], [1, 0]], dtype = "float32")

In [72]:
wts[1] = np.array([1, 0], dtype = "float32")

In [73]:
wts[2] = np.array([[1], [34]], dtype = "float32")
wts[3]= np.zeros(1, dtype = "float32")

In [74]:
model.set_weights(wts)

In [75]:
for ii in range(len(wts)):
    print(wts[ii], "\n")

[[1. 0.]
 [1. 0.]] 

[1. 0.] 

[[ 1.]
 [34.]] 

[0.] 



In [76]:
model.predict(np.array([[1, 3]]))

array([[0.9999092]], dtype=float32)

In [21]:
inputArr = np.array([[1,1]])

Layer1 = np.dot(inputArr, wts[0])
print(Layer1)
Layer2 = np.dot(Layer1, wts[2])
Layer2

[[2. 0.]]


array([[2.]])

In [ ]:
predict

In [ ]:
np.dot(np.array([3,3]), np.array([1,1,1]))