In [1]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from matplotlib.ticker import ScalarFormatter
import os
import pandas as pd
import time
from datetime import datetime
import sys
import seaborn as sns
import scipy.io
import subprocess
import winsound
import pickle
import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score
import tensorflow as tf
print("TensorFlow successfully installed.")
if tf.test.is_built_with_cuda():
    print("The installed version of TensorFlow includes GPU support.")
print(sys.version, "\n")
now = datetime.now()
print("last run on " + str(now))



from keras.layers import Input, Dense, Dropout, BatchNormalization
from keras.models import Model
from keras import regularizers

# Keras callcacks
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
import keras.backend as K

C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


TensorFlow successfully installed.
The installed version of TensorFlow includes GPU support.
3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] 

last run on 2019-05-24 14:49:22.953431


Using TensorFlow backend.


In [2]:
# do a positive and a negative nnet weight cancel

In [3]:
X_train = np.random.rand(4,2 )

In [4]:
X_train.shape

(4, 2)

In [5]:
X_train

array([[0.32075565, 0.30835743],
       [0.81808144, 0.45560212],
       [0.65218752, 0.48304024],
       [0.31589469, 0.11383586]])

In [6]:
Y_train = np.random.rand(X_train.shape[0]).reshape(-1,1) + np.sum(X_train)

In [7]:
Y_train.shape

(4, 1)

In [8]:
K.clear_session()
inputs = Input(shape=(X_train.shape[1],))    

# add layers
x = Dense(2, activation='tanh', )(inputs)
#x = Dense(3, activation='tanh')(x)
predictions = Dense(Y_train.shape[1], activation='linear')(x)

# create model
model = Model(inputs=inputs, outputs=predictions)
model.compile(loss="mean_squared_error", optimizer = "rmsprop", metrics = ['mse'])

In [9]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [10]:
wts = model.get_weights().copy()

In [11]:
wts[0]

array([[ 0.63268065,  0.91927135],
       [-0.37825316,  0.61694574]], dtype=float32)

In [12]:
history = model.fit(X_train, Y_train, epochs = 3, verbose = 2, 
                        batch_size=16)

Epoch 1/3


InternalError: Blas GEMM launch failed : a.shape=(4, 2), b.shape=(2, 2), m=4, n=2, k=2
	 [[Node: dense_1/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_input_1_0_2/_39, dense_1/kernel/read)]]

Caused by op 'dense_1/MatMul', defined at:
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-dae59d0160c3>", line 5, in <module>
    x = Dense(2, activation='tanh', )(inputs)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\keras\engine\topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\keras\layers\core.py", line 855, in call
    output = K.dot(inputs, self.kernel)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\keras\backend\tensorflow_backend.py", line 1072, in dot
    out = tf.matmul(x, y)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2064, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2790, in _mat_mul
    name=name)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\Users\calli\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(4, 2), b.shape=(2, 2), m=4, n=2, k=2
	 [[Node: dense_1/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_input_1_0_2/_39, dense_1/kernel/read)]]


In [ ]:
wts = model.get_weights().copy()
wts

In [70]:
for ii in range(len(wts)):
    print(wts[ii], "\n")

[[-0.22751574  1.0880353 ]
 [-1.1416353  -0.5892527 ]] 

[ 0.00737442 -0.00736383] 

[[ 1.2845858]
 [-0.9695439]] 

[0.00736855] 



In [71]:
wts[0] = np.array([[1, 0], [1, 0]], dtype = "float32")

wts[1] = np.array([1, 0], dtype = "float32")

wts[2] = np.array([[1], [34]], dtype = "float32")
wts[3]= np.zeros(1, dtype = "float32")

model.set_weights(wts)

for ii in range(len(wts)):
    print(wts[ii], "\n")

In [76]:
model.predict(np.array([[1, 3]]))

array([[0.9999092]], dtype=float32)

In [21]:
inputArr = np.array([[1,1]])

Layer1 = np.dot(inputArr, wts[0])
print(Layer1)
Layer2 = np.dot(Layer1, wts[2])
Layer2

[[2. 0.]]


array([[2.]])

In [ ]:
predict

In [ ]:
np.dot(np.array([3,3]), np.array([1,1,1]))