In [1]:
import cv2
cv2.__version__

'3.3.1'

In [2]:
import sys
print(sys.version)

3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]


In [3]:
import numpy as np
import matplotlib
matplotlib.use("TkAgg") # have to use this for tkinter to  work below
from matplotlib import pyplot as plt
%matplotlib tk
import time
import pandas as pd

import skimage.io as io

import os

import imageio
# print environment
os.path.dirname(sys.executable)

'C:\\Users\\calli\\Anaconda3\\envs\\opencv'

In [4]:
# adjust gamma
def adjust_gamma(image, gamma=1.0):
    # build a lookup table mapping the pixel values [0, 255] to
    # their adjusted gamma values
    invGamma = 1.0 / gamma
    table = np.array([((i / 255.0) ** invGamma) * 255
        for i in np.arange(0, 256)]).astype("uint8")
 
    # apply gamma correction using the lookup table
    return cv2.LUT(image, table)

In [5]:
#vidPath = "D:/BeeTwoFlowerExperiment/2018_02_27__14_04_52_556/2018_02_27__14_04_55_680_cam1-0000.avi"
vidPath = r"D:\Dropbox\AcademiaDropbox\dataAnalysisForOthers\SujayFish\BML 17-23.avi"
os.path.isfile(vidPath)

True

In [6]:
# get vid info
cap = cv2.VideoCapture(vidPath)


length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps    = cap.get(cv2.CAP_PROP_FPS)

print(length, width, height, fps)
cap.release()

488 708 480 10.0


In [7]:
def load_imgs(vidPath, start, stop):
    cap = cv2.VideoCapture(vidPath)
    imgs = []
    for ff in range(length):
        
        
        ret, frame = cap.read()
        
        if np.mod(ff, 50) == 0:
            print(ff)
        
    
        # convert to grey
        img = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        
        #adjust gamma
        img = adjust_gamma(img, gamma=3.0)
        
        # convert dtype
        img = img.astype("int16")
        imgs.append(img)
        
        if ff > stop:
            break
            
    cap.release()
    return imgs

In [8]:
imgs = load_imgs(vidPath, 0, length)

0
50
100
150
200
250
300
350
400
450


In [550]:
# normalize images

plt.plot(np.percentile(np.array(imgs), axis = (2,1), q = 0))

In [541]:
plt.matshow(imgs[0] * (255 / np.percentile(np.array(imgs[0]), axis = (0,1), q = 5)))

In [544]:
255 / np.percentile(np.array(imgs[0]), axis = (0,1), q = 5 )

2.3394495412844036

In [546]:
np.percentile(np.array(imgs[0]), axis = (0,1), q = 1 )

105.0

In [493]:
# play video
for ii in range(len(imgs)):
    frame = ((imgs[ii] < 120 )* 255).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [494]:
bkgImg = np.median(np.array(imgs), axis = (0))

In [520]:
# play video
for ii in range(len(imgs)):
    frame = ((imgs[ii] -  bkgImg < -8 )* 255).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   

    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [519]:
# play video
for ii in range(len(imgs)):
    ti = imgs[ii] -  bkgImg
    frame = ((ti + abs(np.min(ti))) / np.max((ti + abs(np.min(ti))))* 255).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   

    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [10]:
np.array(imgs).shape

(488, 480, 708)

In [11]:
imgs[0].shape

(480, 708)

In [27]:
np.percentile(np.array(imgs[290:310]), axis = 0, q =50)

array([[101., 109., 114., ..., 125., 126., 126.],
       [ 99., 108., 112., ..., 125., 126., 126.],
       [ 99., 108., 114., ..., 126., 124., 125.],
       ...,
       [112., 120., 125., ..., 115., 115., 115.],
       [112., 120., 124., ..., 114., 114., 113.],
       [112., 120., 124., ...,  60.,  63.,  60.]])

In [28]:
(np.median(np.array(imgs[290:310]), axis = (0)))

array([[101., 109., 114., ..., 125., 126., 126.],
       [ 99., 108., 112., ..., 125., 126., 126.],
       [ 99., 108., 114., ..., 126., 124., 125.],
       ...,
       [112., 120., 125., ..., 115., 115., 115.],
       [112., 120., 124., ..., 114., 114., 113.],
       [112., 120., 124., ...,  60.,  63.,  60.]])

In [12]:
plt.matshow(imgs[0])
plt.colorbar()
plt.show()

In [21]:
plt.matshow(np.median(np.array(imgs[290:310]), axis = (0)))
plt.colorbar()
plt.show()

In [51]:
plt.matshow(np.percentile(np.array(imgs[280:320]), axis = (0), q =99))
plt.colorbar()
plt.show()

In [42]:
plt.matshow(np.array(imgs[300]))
plt.colorbar()
plt.show()

In [366]:
from scipy import stats

In [345]:
subtractedImgs = []
fnum = 100

In [378]:
fnum += 0
    
medStart = np.max((0,fnum - 30))
medEnd = np.min((length, fnum + 30))



bkgSubtractImg = np.percentile(np.array(imgs[medStart:medEnd]), axis = (0), q = 99.9) - imgs[fnum]
subtractedImgs.append(bkgSubtractImg)
print(fnum)

fig, ax = plt.subplots(2, 1)
img = ax[0].imshow(bkgSubtractImg)
plt.colorbar(img, ax=ax[0])
img2 = ax[1].imshow(imgs[fnum])
plt.colorbar(img2, ax=ax[1])
fnum += 0

100


In [445]:
halfWinLen = 40
subtractedImgs = []


for fnum in range(len(imgs)):
    
    medStart = np.max((0,fnum - halfWinLen))
    medEnd = np.min((length, fnum + halfWinLen))



    bkgSubtractImg = np.percentile(np.array(imgs[medStart:medEnd]), axis = (0), q = 99) - imgs[fnum]
    subtractedImgs.append(bkgSubtractImg)
    
    if np.mod(fnum, 20) == 0:
        print(fnum)

#fig, ax = plt.subplots(2, 1)
# img = ax[0].imshow(bkgSubtractImg)
# plt.colorbar(img, ax=ax[0])
# img2 = ax[1].imshow(imgs[fnum])
# plt.colorbar(img2, ax=ax[1])


0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480


In [477]:
# scale changeImages between 0 and 255
changeBlur = []
for ii in range(len(subtractedImgs)):
    blurredImg = cv2.GaussianBlur(subtractedImgs[ii], (5,5) ,0)
    
    tmpImg = ((255*(blurredImg + abs(np.min(blurredImg))) / 
            np.max(blurredImg+ abs(np.min(blurredImg)))).astype("uint8"))
    
    # invert img
    imagem = cv2.bitwise_not(tmpImg)
    
    changeBlur.append(imagem)

In [478]:
# play video
for ii in range(len(changeBlur)):
    frame = (changeBlur[ii]).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [479]:
# write to file

writeFile = r"D:\Dropbox\AcademiaDropbox\dataAnalysisForOthers\SujayFish\processedVid.avi"

fourcc = cv2.VideoWriter_fourcc(*'XVID')

out = cv2.VideoWriter(writeFile,fourcc, 25.0, (width,height), 0)
for ii in range(len(changeBlur)):
    frame = (changeBlur[ii]).astype("uint8")
    # Display the resulting frame 
    #cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break
    out.write(frame)
out.release()

In [449]:
plt.close("all")

In [456]:
# threshold
# scale changeImages between 0 and 255
threshImg = []
for ii in range(len(changeBlur)):
    tmpImg = ((changeBlur[ii] > 170* 1.0)*255).astype("uint8")
    threshImg.append(tmpImg)

In [457]:
# play video
for ii in range(len(threshImg)):
    frame = (threshImg[ii]).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [432]:
# remove blobs

ii = 200
img, cnts, _ = cv2.findContours(threshImg[ii], cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#     mask = np.ones(threshImg[ii], dtype="uint8") * 0 # create a blank black mask

In [433]:
areas = np.array([cv2.contourArea(c, False) for c in cnts])

In [434]:
frame = (threshImg[ii]).astype("uint8")
    
# Display the resulting frame 
cv2.imshow('Frame', frame) 

In [435]:
areas

array([6.000e+00, 2.500e+00, 3.100e+01, 1.600e+01, 1.750e+01, 1.050e+01,
       2.300e+01, 5.600e+01, 5.300e+01, 4.800e+01, 1.000e+02, 1.990e+02,
       4.450e+01, 6.395e+02, 4.000e+00, 2.000e+00, 4.750e+01, 8.000e+00,
       9.000e+00, 3.500e+00, 3.500e+00, 2.750e+01, 3.500e+01, 2.000e+00,
       1.950e+01, 4.000e+01, 2.050e+01, 2.650e+01, 2.550e+01, 7.750e+01,
       1.500e+00, 7.000e+00, 7.600e+01, 3.600e+01, 1.700e+01, 1.000e+01,
       0.000e+00, 2.050e+01, 1.280e+02, 8.500e+00, 2.500e+00, 4.750e+01,
       1.955e+02, 1.400e+01, 2.595e+02, 1.840e+02, 4.300e+01, 2.558e+03,
       0.000e+00, 1.160e+02, 9.800e+01, 6.000e+01])

In [444]:
plt.plot(np.median(np.array(changeBlur), axis = (1,2)))
plt.show()

In [ ]:

# over time, the background gets lighter
# 0 is black, 255 is white
plt.clf()
plt.plot(np.median(np.array(imgs), axis = (1,2)))
plt.show()

In [511]:
# calculate changing background
window_length = 20
vidLen = length


bkgList = []

for ii in np.arange(1, length):
    
    if np.mod(ii, 50) == 0:
        print(ii)
    start = np.max((0, ii-(window_length//2)))
    endd = np.min((vidLen, ii+(window_length//2) ))
        
    tmpBkg = np.median(np.array(imgs)[start:endd, :, :], axis = (0))
    bkgList.append(tmpBkg)

50
100
150
200
250
300
350
400
450


In [515]:

# play video
for ii in np.arange(1,len(imgs)):
    frame = ((imgs[ii] -  bkgList[ii-1] < 5)* 255).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   

    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [ ]:
plt.plot(np.median(np.array(bkgList), axis = (1,2)))

In [ ]:
# play video
for ii in range(len(bkgList)):
    frame = (bkgList[ii]).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [ ]:
# subtract background
imArray = np.array(imgs)

# threshold only stuff that gets darker ( that is, change is > 0)""
changeImgs = np.array([(bkgList[ii] - imArray[ii, :, :])  for ii in range(len(bkgList))])

In [ ]:
# subtract background
imArray = np.array(imgs)

# threshold only stuff that gets darker ( that is, change is > 0)""
changeImgs = np.array([(bkgImg - imArray[ii, :, :]) for ii in range(len(bkgList))])

In [ ]:
plt.matshow(changeImgs[10])

In [ ]:
plt.hist(changeImgs[200].flatten())

In [ ]:
len(changeImgs)

In [ ]:
ii = 0 
frame = (changeImgs[ii]).astype("uint8")
cv2.imshow('Frame', frame) 

In [ ]:
# subtract background
imArray = np.array(imgs)

# threshold only stuff that gets darker ( that is, change is > 0)""
changeImgs = np.array([(bkgImg - imArray[ii, :, :]) for ii in range(len(bkgList))])

In [ ]:
# scale changeImages between 0 and 255
changeBlur = []
for ii in range(len(changeImgs)):
    blurredImg = cv2.GaussianBlur(changeImgs[ii], (15,15) ,0)
    
    tmpImg = ((255*(blurredImg + abs(np.min(blurredImg))) / 
            np.max(blurredImg+ abs(np.min(blurredImg)))).astype("uint8"))
    
    changeBlur.append(tmpImg)
    

In [ ]:
# play video
for ii in range(len(changeBlur)):
    frame = (changeBlur[ii]).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [ ]:
tmpImg = ((255*(changeBlur[0] + abs(np.min(changeBlur[0]))) / 
np.max(changeBlur[0] + abs(np.min(changeBlur[0])))).astype("uint8"))

In [ ]:
cv2.imshow('Frame', tmpImg) 

In [ ]:
plt.matshow(blur)

In [ ]:
ii =30
frame = (changeImgs[ii] + 80).astype("uint8")
cv2.imshow('Frame', frame) 

In [ ]:
plt.matshow(changeImgs[0])

In [ ]:
# play video
for ii in range(len(changeImgs)):
    frame = (changeImgs[ii] + 80).astype("uint8")
    
    # Display the resulting frame 
    cv2.imshow('Frame', frame) 
   
    # Press Q on keyboard to  exit 
    if cv2.waitKey(25) & 0xFF == ord('q'): 
        break

In [ ]:
# # calculate background image
# # check dtype
#     if calImg.dtype != "int16":
#         calImg = calImg.astype('int16') 
#     if frame.dtype != "int16":
#         frame = frame.astype('int16')
    
#     # get image difference
#     im1Diff = (calImg - frame) 
#     height,width = im1Diff.shape
    
#     # crop image to a circle
#     mask_circ = np.zeros((height,width), np.uint8)
#     cv2.circle(mask_circ,(int(width/2),int(height/2)),int(np.min([width,height])/2),(255),thickness=-1)
#     imDiff_cropped = cv2.bitwise_and(im1Diff, im1Diff, mask=mask_circ)

#     # gaussian blur
#     # 121, 121 works for full sized image, 15,15 works for 4x smaller image
#     # 5,5 works for 1/10 size
#     blur = cv2.GaussianBlur(imDiff_cropped, blurAmt ,0)
    
#     # get darker sections (positive threshold gives dark areas)
#     ret_dark,th3_dark = cv2.threshold(blur,70,255,cv2.THRESH_BINARY)
    
#     # get areas
#     img, cnts, _ = cv2.findContours(th3_dark.astype('uint8'), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
#     mask = np.ones(th3_dark.shape[:2], dtype="uint8") * 0 # create a blank black mask

#     areas = np.array([cv2.contourArea(c, False) for c in cnts])